"""ffmpeg compositor: storyboard -> final .mp4.

Text is rendered by Chromium (reel.textlayer) as transparent PNGs — the browser
shapes Arabic correctly (connected, RTL), which the bundled ffmpeg/libass does
NOT. So ffmpeg's only text job is to OVERLAY those PNGs (with an alpha fade) on
each scene clip; it never shapes text itself.

Stages (kept separate so a failure is legible):
  1. Render one transparent text PNG per scene (single browser session).
  2. Per scene: the provider generates a text-free clip; normalize to a uniform
     WxH / fps / timebase / pix_fmt and overlay the scene's text PNG (alpha fade).
  3. Concat the scene clips (hard cuts; identical params -> stream copy).
  4. Mux optional music with fades; finalize H.264 + faststart.

Hard cuts + per-scene text fades (robust) rather than xfade crossfades (a future
polish item).
"""
from __future__ import annotations

import sys
import tempfile
from pathlib import Path
from typing import Any, Optional

from .ffmpeg_tools import run_ffmpeg
from .schemas import REEL_H, REEL_W, ReelRenderResult, Storyboard
from .textlayer import render_text_sequences
from .video_provider import KenBurnsProvider, VideoProvider


def _even(n: float) -> int:
    return int(n) // 2 * 2          # libx264 yuv420p needs even dimensions


def render_reel(
    storyboard: Storyboard,
    *,
    provider: VideoProvider,
    out_path: str | Path,
    fps: int = 30,
    scale: float = 1.0,
    music_path: Optional[str | Path] = None,
    voiceover_path: Optional[str | Path] = None,
    include_logo: bool = True,
    fallback_provider: Optional[VideoProvider] = None,
    qa_caller: Any = None,
    qa_product_hint: Optional[str] = None,
    qa_reference_image: Optional[bytes] = None,
) -> ReelRenderResult:
    """Render the storyboard to `out_path`. `scale` (<1) renders a faster, smaller
    preview; the text PNGs are rendered at the same scaled size so overlay is 1:1.

    `fallback_provider` saves the reel when the primary provider fails on a scene
    (e.g. Veo 404 on an unprovisioned model, 429/quota, or a timeout): instead of
    crashing the whole render, that ONE scene is regenerated by the fallback.
    Default = a KenBurns pass over the brand's REAL scraped photos (degrade to the
    actual place, not a blank gradient), which itself degrades to a palette gradient
    when there are no usable photos. So a render NEVER hard-fails on a provider error.

    `qa_caller` (a multimodal caller) turns on the SCENE QA gate: each generated clip is
    inspected against `qa_reference_image` (the real product photo) + `qa_product_hint`
    (its name); a clip where the product is unfaithful, vanishes, or does an impossible
    action is regenerated ONCE, then falls back to the faithful real-photo KenBurns — so a
    Veo hallucination never ships (the owner: 'it presses a sealed pump and then vanishes').
    QA is off (identical old behaviour) when qa_caller is None.
    """
    out_path = Path(out_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    W, H = _even(REEL_W * scale), _even(REEL_H * scale)
    fade = 0.4
    # CALIBRATION FINDING (2026-07-12): Veo draws garbled text onto signs/equipment and
    # the motion QA rightly kills the clip — a wasted render. Ban it at the prompt, for
    # every scene, retry and fallback — including OLD plans and HITL-edited ones.
    _NO_TEXT = (" Absolutely no readable text anywhere in the scene — no signage, screen "
                "text, labels, posters or logos; any text-bearing surface stays abstract, "
                "blurred or out of frame.")
    fallback_used = (provider.name == "stub")
    scene_qa: list = []   # per-scene motion-QA verdicts (exported on the audit trail)
    fb = fallback_provider or KenBurnsProvider(
        storyboard.content_images, fallback_palette=storyboard.palette_hex or None
    )

    with tempfile.TemporaryDirectory(prefix="reel_") as tmp:
        tmpd = Path(tmp)

        # 1) KINETIC text layer — one PNG SEQUENCE per scene (Chromium shapes Arabic
        # correctly AND drives the per-element entrance: headline pop -> sublines -> CTA).
        text_seqs = render_text_sequences(
            storyboard, width=W, height=H, fps=fps, out_dir=tmpd, include_logo=include_logo,
        )

        # 2) per scene: text-free clip -> normalize + overlay text (alpha fade).
        # GROUNDING: every scene is SEEDED from its own REAL scraped photo
        # (scene.seed_image_url, a distinct content photo). KenBurns animates it;
        # Veo 3.1 brings it to life. So the whole reel comes from the real place,
        # not one repeated frame. Falls back to the hero only if a scene has no seed.
        norm_clips: list[Path] = []
        for i, scene in enumerate(storyboard.scenes):
            ref = scene.seed_image_url or (
                storyboard.reference_image_url if scene.kind in ("intro", "outro") else None
            )
            gen_kwargs = dict(
                out_path=tmpd / f"raw{i}.mp4",
                duration_s=scene.duration_s,
                width=W, height=H,
                palette=storyboard.palette_hex,
                reference_image=ref,
            )
            try:
                raw = provider.generate(scene.visual_prompt + _NO_TEXT, **gen_kwargs)
            except Exception as exc:                       # noqa: BLE001
                # A provider failure on ONE scene must not kill the whole reel.
                # Regenerate just this scene with the fallback (real-photo KenBurns
                # -> palette gradient). Observable in the log so a degraded reel is
                # never silently passed off as a full provider render.
                print(
                    f"[reel] scene {i} provider '{provider.name}' failed "
                    f"({type(exc).__name__}: {exc}); falling back to '{fb.name}'",
                    file=sys.stderr,
                )
                fallback_used = True
                raw = fb.generate(scene.visual_prompt + _NO_TEXT, **gen_kwargs)
            else:
                # SCENE QA GATE (opt-in via qa_caller): reject a Veo clip where the product is
                # unfaithful / vanishes / does an impossible action — or (motion-QA extension,
                # 2026-07-12) faces warp, objects morph, junk pseudo-text appears, the footage
                # isn't ad-grade, or the WORLD drifts from the real seed (calibrated: the
                # owner's 'old school' scene fails against its real seed) — regenerate ONCE,
                # then fall back to the FAITHFUL real-photo KenBurns so a hallucination never
                # ships. Service brands too: with no product reference, the scene's OWN
                # real-photo seed is the reference.
                if qa_caller is not None:
                    from .scene_qa import check_scene
                    _v_final = None
                    qa_ref = qa_reference_image
                    # owner ruling 2026-07-12: generated seeds — the judge compares the
                    # clip against the brand's REAL photo, not the generated still.
                    ref_for_qa = getattr(scene, "place_ref_url", None) or ref
                    if qa_ref is None and ref_for_qa:
                        try:
                            from .video_provider import _load_reference_image
                            loaded = _load_reference_image(ref_for_qa)
                            qa_ref = loaded[0] if loaded else None
                        except Exception:  # noqa: BLE001 — no seed bytes: judge frames alone
                            qa_ref = None
                    v = check_scene(raw, product_hint=qa_product_hint,
                                    reference_image=qa_ref, caller=qa_caller)
                    _v_final = v
                    if v.checked and not v.overall_pass:
                        print(f"[reel] scene {i} QA fail ({v.reason}); regenerating once",
                              file=sys.stderr)
                        good = False
                        try:
                            raw = provider.generate(scene.visual_prompt + _NO_TEXT, **gen_kwargs)
                            v2 = check_scene(raw, product_hint=qa_product_hint,
                                             reference_image=qa_ref, caller=qa_caller)
                            _v_final = v2
                            good = (not v2.checked) or v2.overall_pass
                        except Exception:  # noqa: BLE001 — a failed retry drops to the fallback
                            good = False
                        if not good:
                            print(f"[reel] scene {i} still failed QA; faithful seed-frame KenBurns fallback",
                                  file=sys.stderr)
                            fallback_used = True
                            raw = fb.generate(scene.visual_prompt + _NO_TEXT, **gen_kwargs)
                    if _v_final is not None:
                        scene_qa.append({"scene": i, **_v_final.model_dump()})
            norm = tmpd / f"norm{i}.mp4"
            d = scene.duration_s
            fout = max(0.0, d - fade)
            # The kinetic PNG SEQUENCE already carries the per-element entrance (pop /
            # slide-up / staggered fade), so the overlay no longer block-slides. We feed
            # the sequence via the image2 demuxer at `fps`, HOLD its last frame for the
            # rest of the scene (tpad clone), and keep the scene-end alpha fade-out for a
            # clean cut. The sequence starts at the scene's first frame (t=0).
            fc = (
                f"[0:v]scale={W}:{H}:force_original_aspect_ratio=increase,"
                f"crop={W}:{H},settb=AVTB,fps={fps},format=yuv420p[bg];"
                f"[1:v]format=rgba,fps={fps},tpad=stop_mode=clone:stop_duration={d:.2f},"
                f"settb=AVTB,fade=t=out:st={fout:.2f}:d={fade}:alpha=1[tx];"
                f"[bg][tx]overlay=x=0:y=0:format=auto,format=yuv420p[v]"
            )
            run_ffmpeg([
                "-i", str(raw),
                "-framerate", str(fps), "-start_number", "0", "-i", str(text_seqs[i]),
                "-filter_complex", fc, "-map", "[v]", "-t", f"{d:.2f}",
                "-c:v", "libx264", "-pix_fmt", "yuv420p",
                "-profile:v", "high", "-preset", "medium", "-crf", "20",
                str(norm),
            ])
            norm_clips.append(norm)

        # 3) concat (identical params -> stream copy).
        listfile = tmpd / "concat.txt"
        listfile.write_text(
            "".join(f"file '{c.as_posix()}'\n" for c in norm_clips), encoding="utf-8"
        )
        bg = tmpd / "bg.mp4"
        run_ffmpeg(["-f", "concat", "-safe", "0", "-i", str(listfile), "-c", "copy", str(bg)])

        # 4) finalize, muxing optional voice-over (primary) + music (ducked under it).
        total = storyboard.total_duration_s
        has_vo = bool(voiceover_path and Path(voiceover_path).is_file())
        has_music = bool(music_path and Path(music_path).is_file())
        has_audio = has_vo or has_music
        if has_vo and has_music:
            # VO at full level; music faded + ducked to a quiet bed beneath it.
            run_ffmpeg([
                "-i", str(bg), "-i", str(Path(voiceover_path).resolve()),
                "-i", str(Path(music_path).resolve()),
                "-filter_complex",
                f"[2:a]volume=0.18,afade=t=in:st=0:d=1.0,"
                f"afade=t=out:st={max(0.0, total - 1.5):.2f}:d=1.5[m];"
                f"[1:a][m]amix=inputs=2:duration=first:dropout_transition=0[a]",
                "-map", "0:v", "-map", "[a]",
                "-c:v", "copy", "-c:a", "aac", "-b:a", "192k", "-shortest",
                "-movflags", "+faststart", str(out_path.resolve()),
            ])
        elif has_vo:
            run_ffmpeg([
                "-i", str(bg), "-i", str(Path(voiceover_path).resolve()),
                "-map", "0:v", "-map", "1:a",
                "-c:v", "copy", "-c:a", "aac", "-b:a", "192k", "-shortest",
                "-movflags", "+faststart", str(out_path.resolve()),
            ])
        elif has_music:
            run_ffmpeg([
                "-i", str(bg), "-i", str(Path(music_path).resolve()),
                "-filter_complex",
                f"[1:a]afade=t=in:st=0:d=1.0,"
                f"afade=t=out:st={max(0.0, total - 1.5):.2f}:d=1.5[a]",
                "-map", "0:v", "-map", "[a]",
                "-c:v", "copy", "-c:a", "aac", "-b:a", "192k", "-shortest",
                "-movflags", "+faststart", str(out_path.resolve()),
            ])
        else:
            run_ffmpeg([
                "-i", str(bg), "-c", "copy", "-movflags", "+faststart",
                str(out_path.resolve()),
            ])

    return ReelRenderResult(
        reel_path=str(out_path), filename=out_path.name,
        width=W, height=H, duration_s=storyboard.total_duration_s, fps=fps,
        provider=provider.name, fallback_used=fallback_used, has_audio=has_audio,
        scene_qa=scene_qa,
    )
