"""ffmpeg compositor: storyboard -> final .mp4.

Text is rendered by Chromium (reel.textlayer) as transparent PNGs — the browser
shapes Arabic correctly (connected, RTL), which the bundled ffmpeg/libass does
NOT. So ffmpeg's only text job is to OVERLAY those PNGs (with an alpha fade) on
each scene clip; it never shapes text itself.

Stages (kept separate so a failure is legible):
  1. Render one transparent text PNG per scene (single browser session).
  2. Per scene: the provider generates a text-free clip; normalize to a uniform
     WxH / fps / timebase / pix_fmt and overlay the scene's text PNG (alpha fade).
  3. Concat the scene clips (hard cuts; identical params -> stream copy).
  4. Mux optional music with fades; finalize H.264 + faststart.

Hard cuts + per-scene text fades (robust) rather than xfade crossfades (a future
polish item).
"""
from __future__ import annotations

import sys
import tempfile
from pathlib import Path
from typing import Optional

from .ffmpeg_tools import run_ffmpeg
from .schemas import REEL_H, REEL_W, ReelRenderResult, Storyboard
from .textlayer import render_text_layers
from .video_provider import KenBurnsProvider, VideoProvider


def _even(n: float) -> int:
    return int(n) // 2 * 2          # libx264 yuv420p needs even dimensions


def render_reel(
    storyboard: Storyboard,
    *,
    provider: VideoProvider,
    out_path: str | Path,
    fps: int = 30,
    scale: float = 1.0,
    music_path: Optional[str | Path] = None,
    voiceover_path: Optional[str | Path] = None,
    include_logo: bool = True,
    fallback_provider: Optional[VideoProvider] = None,
) -> ReelRenderResult:
    """Render the storyboard to `out_path`. `scale` (<1) renders a faster, smaller
    preview; the text PNGs are rendered at the same scaled size so overlay is 1:1.

    `fallback_provider` saves the reel when the primary provider fails on a scene
    (e.g. Veo 404 on an unprovisioned model, 429/quota, or a timeout): instead of
    crashing the whole render, that ONE scene is regenerated by the fallback.
    Default = a KenBurns pass over the brand's REAL scraped photos (degrade to the
    actual place, not a blank gradient), which itself degrades to a palette gradient
    when there are no usable photos. So a render NEVER hard-fails on a provider error.
    """
    out_path = Path(out_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    W, H = _even(REEL_W * scale), _even(REEL_H * scale)
    fade = 0.4
    fallback_used = (provider.name == "stub")
    fb = fallback_provider or KenBurnsProvider(
        storyboard.content_images, fallback_palette=storyboard.palette_hex or None
    )

    with tempfile.TemporaryDirectory(prefix="reel_") as tmp:
        tmpd = Path(tmp)

        # 1) text layer PNGs (Chromium shapes Arabic correctly).
        text_pngs = render_text_layers(
            storyboard, width=W, height=H, out_dir=tmpd, include_logo=include_logo,
        )

        # 2) per scene: text-free clip -> normalize + overlay text (alpha fade).
        # GROUNDING: every scene is SEEDED from its own REAL scraped photo
        # (scene.seed_image_url, a distinct content photo). KenBurns animates it;
        # Veo 3.1 brings it to life. So the whole reel comes from the real place,
        # not one repeated frame. Falls back to the hero only if a scene has no seed.
        norm_clips: list[Path] = []
        for i, scene in enumerate(storyboard.scenes):
            ref = scene.seed_image_url or (
                storyboard.reference_image_url if scene.kind in ("intro", "outro") else None
            )
            gen_kwargs = dict(
                out_path=tmpd / f"raw{i}.mp4",
                duration_s=scene.duration_s,
                width=W, height=H,
                palette=storyboard.palette_hex,
                reference_image=ref,
            )
            try:
                raw = provider.generate(scene.visual_prompt, **gen_kwargs)
            except Exception as exc:                       # noqa: BLE001
                # A provider failure on ONE scene must not kill the whole reel.
                # Regenerate just this scene with the fallback (real-photo KenBurns
                # -> palette gradient). Observable in the log so a degraded reel is
                # never silently passed off as a full provider render.
                print(
                    f"[reel] scene {i} provider '{provider.name}' failed "
                    f"({type(exc).__name__}: {exc}); falling back to '{fb.name}'",
                    file=sys.stderr,
                )
                fallback_used = True
                raw = fb.generate(scene.visual_prompt, **gen_kwargs)
            norm = tmpd / f"norm{i}.mp4"
            d = scene.duration_s
            fout = max(0.0, d - fade)
            # Text layer: fade in/out (alpha) AND a slide-up entrance (overlay y
            # eases from a small offset to 0 over ~0.5s) so the text feels alive,
            # not static. The y expression is single-quoted to protect its commas
            # inside the filtergraph.
            fc = (
                f"[0:v]scale={W}:{H}:force_original_aspect_ratio=increase,"
                f"crop={W}:{H},settb=AVTB,fps={fps},format=yuv420p[bg];"
                f"[1:v]format=rgba,fade=t=in:st=0:d={fade}:alpha=1,"
                f"fade=t=out:st={fout:.2f}:d={fade}:alpha=1[tx];"
                f"[bg][tx]overlay=x=0:y='(main_h*0.035)*pow(max(0,1-t/0.6),3)':format=auto,"
                f"format=yuv420p[v]"
            )
            run_ffmpeg([
                "-i", str(raw), "-loop", "1", "-i", str(text_pngs[i]),
                "-filter_complex", fc, "-map", "[v]", "-t", f"{d:.2f}",
                "-c:v", "libx264", "-pix_fmt", "yuv420p",
                "-profile:v", "high", "-preset", "medium", "-crf", "20",
                str(norm),
            ])
            norm_clips.append(norm)

        # 3) concat (identical params -> stream copy).
        listfile = tmpd / "concat.txt"
        listfile.write_text(
            "".join(f"file '{c.as_posix()}'\n" for c in norm_clips), encoding="utf-8"
        )
        bg = tmpd / "bg.mp4"
        run_ffmpeg(["-f", "concat", "-safe", "0", "-i", str(listfile), "-c", "copy", str(bg)])

        # 4) finalize, muxing optional voice-over (primary) + music (ducked under it).
        total = storyboard.total_duration_s
        has_vo = bool(voiceover_path and Path(voiceover_path).is_file())
        has_music = bool(music_path and Path(music_path).is_file())
        has_audio = has_vo or has_music
        if has_vo and has_music:
            # VO at full level; music faded + ducked to a quiet bed beneath it.
            run_ffmpeg([
                "-i", str(bg), "-i", str(Path(voiceover_path).resolve()),
                "-i", str(Path(music_path).resolve()),
                "-filter_complex",
                f"[2:a]volume=0.18,afade=t=in:st=0:d=1.0,"
                f"afade=t=out:st={max(0.0, total - 1.5):.2f}:d=1.5[m];"
                f"[1:a][m]amix=inputs=2:duration=first:dropout_transition=0[a]",
                "-map", "0:v", "-map", "[a]",
                "-c:v", "copy", "-c:a", "aac", "-b:a", "192k", "-shortest",
                "-movflags", "+faststart", str(out_path.resolve()),
            ])
        elif has_vo:
            run_ffmpeg([
                "-i", str(bg), "-i", str(Path(voiceover_path).resolve()),
                "-map", "0:v", "-map", "1:a",
                "-c:v", "copy", "-c:a", "aac", "-b:a", "192k", "-shortest",
                "-movflags", "+faststart", str(out_path.resolve()),
            ])
        elif has_music:
            run_ffmpeg([
                "-i", str(bg), "-i", str(Path(music_path).resolve()),
                "-filter_complex",
                f"[1:a]afade=t=in:st=0:d=1.0,"
                f"afade=t=out:st={max(0.0, total - 1.5):.2f}:d=1.5[a]",
                "-map", "0:v", "-map", "[a]",
                "-c:v", "copy", "-c:a", "aac", "-b:a", "192k", "-shortest",
                "-movflags", "+faststart", str(out_path.resolve()),
            ])
        else:
            run_ffmpeg([
                "-i", str(bg), "-c", "copy", "-movflags", "+faststart",
                str(out_path.resolve()),
            ])

    return ReelRenderResult(
        reel_path=str(out_path), filename=out_path.name,
        width=W, height=H, duration_s=storyboard.total_duration_s, fps=fps,
        provider=provider.name, fallback_used=fallback_used, has_audio=has_audio,
    )
